apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: webserver-deploy
  name: webserver-deploy
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: webserver-deploy
status:
  loadBalancer: {}
